<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion>
    <AssemblyName>AffineSingle.Managed</AssemblyName><Version>8.0.0</Version>
    <DefineConstants>$(DefineConstants);AFFINE_NATIVE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Lighting\**\*.cs" />
    <Reference Include="MelonLoader"><HintPath>$(MelonLoaderDir)\MelonLoader.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(MelonLoaderDir)\0Harmony.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
