<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion></PropertyGroup><ItemGroup><Compile Include="..\managed\PhysicalCoinBridge.cs" Link="PhysicalCoinBridge.cs"/><Reference Include="0Harmony"><HintPath>$(MelonLoaderDir)\0Harmony.dll</HintPath></Reference><Reference Include="MelonLoader"><HintPath>$(MelonLoaderDir)\MelonLoader.dll</HintPath></Reference></ItemGroup></Project>
